version: '3.7'

x-ldap_admin_env: &ldap_admin_env
  # FIXME: take from env (which should be set to random)
  LDAP_ADMIN_PASSWORD: &ldapadminpass ldapadminpwd # pragma: allowlist secret
  LDAP_ADMIN_USERNAME: &ldapadminuser admin

services:
  openldap:
    image: pvarki/openldap:latest
    build:
      dockerfile: Dockerfile
    ports:
      - '1389:1389'
    environment:
      <<: *ldap_admin_env
      LDAP_SKIP_DEFAULT_TREE: yes
      LDAP_ALLOW_ANON_BINDING: no
      # FIXME: get from env ??
      LDAP_ROOT: "dc=example,dc=org"  # Probably needs to match the custom ldfis
#      LDAP_LOGLEVEL: -1
      # FIXME: Use letsencrypt cert ?
      #LDAP_ENABLE_TLS: 1
      #LDAP_TLS_CERT_FILE: /opt/bitnami/openldap/certs/openldap.crt
      #LDAP_TLS_KEY_FILE: /opt/bitnami/openldap/certs/openldap.key
      #LDAP_TLS_CA_FILE: /opt/bitnami/openldap/certs/openldapCA.crt
    volumes:
      - openldap_data:/bitnami/openldap
    healthcheck:
      test: 'ldapsearch -Q -tt -LLL -Y EXTERNAL -H ldapi:/// "(uid=testuser)" -b dc=example,dc=org memberOf'
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  openldap_data:
