on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  OPENLDAP_VERSION_TAG: 2.5.14

jobs:
  publish:
    name: Publish Docker image
    runs-on: arc-runner-set
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - name: Publish Docker image
        uses: pvarki/config-ci-library/.github/actions/publish-image@main
        with:
          product: openldap
          component: server
          dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          acr-repo: ${{ vars.ACR_REPO }}
          acr-username: ${{ vars.ACR_USERNAME }}
          acr-token: ${{ secrets.ACR_TOKEN }}
          extra-tag: "OPENLDAP-${{ env.OPENLDAP_VERSION_TAG }}"
